version: '3.5'
services:
  #nginx 
  web:
    build: .
    image: web
    container_name: web    
    ports:
     - "80:80"
    expose:
      - "80"
    environment:
       NGINX_HOST: testecielo.com
       NGINX_PORT: 80
    networks:
      - web

# Network
networks:
  web:
    name: web